### PR TITLE
Feature/word wrap

### PR DESCRIPTION
**Pull request by jcwinkler**
Implements word wrap feature incl. storage of config, see issue #47 

Some major changes were necessary in `asktext.py` to ensure that this feature is also available in GTK version of GUI without GTKSourceView.

### CODE REVIEW

**Comment by jcwinkler** [comment]
GTK GUI -> see issue #47 

TK version:

grafik

grafik

**Comment by sizmailov** [comment]
Found two bugs: 
 - The "word wrap" setting is stored/read properly, but it does not affect actual word wrap, see screenshot 
 - Duplicate of word wrap checkbox appears in UI, should be just one in `View` menu

image

**Comment by jcwinkler** [comment]
> The "word wrap" setting is stored/read properly, but it does not affect actual word wrap, see screenshot

Fixed.

> Duplicate of word wrap checkbox appears in UI, should be just one in `View` menu

I did this intentionally to offer a "quick access".

**Comment by sizmailov** [comment]
> I did this intentionally to offer a "quick access".

It's not a good idea, simply because the need of switch is too infrequent. You will probably do it once per installation. 
At the same time it takes valuable space.

**Comment by jcwinkler** [comment]
After one week of work with the modified extension I have to admit that it is enough to have the word wrap switch in the menu. I removed the checkbox.

**Pull request merged**
