### PR TITLE
Store node text in base64 (in addition to plain string)

### PR DESCRIPTION
**Pull request by sizmailov**
This PR add extra field `data-base64-text` to TexText nodes with base64-encoded `text` field. 
Encoded value is hardened against legit transformations over svg attributes (which we cannot control) and helps us keep user input intact, unlike plain text attribute. 

Plain text `text` attribute is kept for backward compatibility and used as fallback.

Related issue(s):
#265

Short checklist:
- [X] Tested with Inkscape version: [Inkscape 1.1-dev (cfef7036a0, 2020-11-10)]
- [X] Tested on Linux, Distro: [Ubuntu 20.04.1 LTS]
- [ ] Tested on Windows, Version: [fill in Windows version here]
- [ ] Tested on MacOS, Version:  [fill in MacOS version/ name here]

### CODE REVIEW

**Comment by sizmailov** [comment]
Here is and example when this PR becomes handy. 
Complex formulae usually span multiple rows, especially when it comes to matrices, etc. 

<details><summary>Before/After</summary>

Formula:

image

Before:
image

After:
image

</details>

**Comment by jcwinkler** [comment]
Thanks, @sizmailov for the quick response. I will merge this and make a bugfix release during this day.

**Comment by jcwinkler** [comment]
@sizmailov Could you rebase your commit onto develop, please? Thanks!

**Comment by sizmailov** [comment]
Hi. I'm now thinking that I was too eager with this PR. May be we should revert to string escaping scheme instead? It has no problems with spaces/new lines and would not bloat the resulting SVG. 

Anyhow this PR won't solve #265, there is no rush with it. I'll turn it into a draft for the moment.

**Pull request closed without merging**
