### PR TITLE
Port to inkscape 1.0

### PR DESCRIPTION
**Pull request by sizmailov**
Updated version of TexText is NOT going to be compatible with inkscape<1.0.

List of changes to make:

 - [x] Remove pstoedit / pdf2svg dependencies (#131)
 - [x] Remove usage of deprecated inkex API (#107)
 - [x] Replace pyGTK with PyGObject+GTK3 (#122) (almost done `in feature/port_to_gtk3` branch, but is not in this PR yet)
 - [x] Make extension python2/python3 compatible
 - [ ] Check forward/backward compatibility of resulting svg with older TexText+Inkscape versions
 - [x] Adjust tests (inkscape cli changed)
 - [ ] Adjust CI (inkscape1.0 is not released yet, so it will be not available in CI, do only backward forward comp. checks)
 - ~~Make PYPI pacakge and support installation via inkscape extension manager (#132)~~ (should  go to separate PR)

Precise description of the changes proposed in the pull request:

Short checklist:
- [x] Tested with Inkscape version: [1.0alpha2]
- [x] Tested on Linux, Distro: [Ubuntu 18.04.2]
- [ ] Tested on Windows, Version: [fill in Windows version here]
- [ ] Tested on MacOS, Version:  [fill in MacOS version/ name here]

### CODE REVIEW

**Comment by jcwinkler** [comment]
I think we do need a transition to Python3 as well?

**Comment by sizmailov** [comment]
@jcwinkler Thanks, updated checklist

**Comment by sizmailov** [comment]
Extension is basically functional with master of inkscape and inkscape/extensions.

**Comment by jcwinkler** [comment]
> Make extension python2/python3 compatible

Do we really need compatibility to Python2 anymore? I think Python3 compatibility is OK or am I wrong?

**Comment by sizmailov** [comment]
The answers whether python2 support is required varies in time. I think dev team did't come to 100% agreement. I think it will not take too much time, so I'll do it.

**Comment by jcwinkler** [comment]
OK. At least for Windows there will be Python3 support only. I already prepared the package together with ede123: https://gitlab.com/inkscape/extensions/issues/85

I will give you more information this evening.

**Comment by sizmailov** [comment]
The extension is working with Inkscape 1.0alpha2 + inkex (master)

The old way of comparing in tests is not longer valid, since code for pstoedit/pdf2svg converters are gone now.

I'm inclined to disable current set of tests.

**Comment by jcwinkler** [comment]
Thank you very much @sizmailov !

Under Windows TexText is not shown in the extension menu with Inkscape alpha2. The error messages thrown when Inkscape is launched from the command line read:

```
** (inkscape.exe:2948): WARNING **: 13:20:22.536: Failed to find resource file '
textext.py'. Looked in:
        C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext.py
        c:\Program Files (x86)\inkscape\share\inkscape\extensions\textext.py

** (inkscape.exe:2948): WARNING **: 13:20:22.536: Failed to find resource file '
asktext.py'. Looked in:
        C:\Users\winkler\AppData\Roaming\inkscape\extensions\asktext.py
        c:\Program Files (x86)\inkscape\share\inkscape\extensions\asktext.py

** (inkscape.exe:2948): WARNING **: 13:20:22.536: Failed to find resource file '
typesetter.py'. Looked in:
        C:\Users\winkler\AppData\Roaming\inkscape\extensions\typesetter.py
        c:\Program Files (x86)\inkscape\share\inkscape\extensions\typesetter.py

** (inkscape.exe:2948): WARNING **: 13:20:22.536: Failed to find resource file '
latexlogparser.py'. Looked in:
        C:\Users\winkler\AppData\Roaming\inkscape\extensions\latexlogparser.py
        c:\Program Files (x86)\inkscape\share\inkscape\extensions\latexlogparser
.py

** (inkscape.exe:2948): WARNING **: 13:20:22.536: Failed to find resource file '
textext.py'. Looked in:
        C:\Users\winkler\AppData\Roaming\inkscape\extensions\textext.py
        c:\Program Files (x86)\inkscape\share\inkscape\extensions\textext.py
```

**This can be fixed as follows:**
- Move all TexText files from the textext subdir into the user extension main dir
- Rename ``__init.py__`` to ``textext.py``
- Keep OR remove text textext-subir-names from the file specs in ``textext.inx``

It seems that Inkscape does not look in the textext subdir although it is specified in ``textext.inx`` ?? And further does not like the ``__init.py__`` ...  An Inkscape bug? Should I file there?

**Comment by sizmailov** [comment]
It feels like inkscape bug. Some work was done with the `.inx` subsystem, so it equally might be intentional change. @ede123 what would you say? 

On the other hand we kind of misuse `__init__.py` for historically reasons, I think. It should be divided into number of smaller parts. The main file should be named `__main__.py` to follow python conventions.

**Comment by sizmailov** [comment]
Just to double check. @jcwinkler Are you sure that you are using current version of the TexText? Can you look into `textext.inx` on your system?

**Comment by jcwinkler** [comment]
textext.inx:
``` xml
<inkscape-extension>
  <_name>Tex Text</_name>
  <id>org.ekips.filter.textext</id>
  <dependency type="executable" location="extensions">textext/__init__.py</dependency>
  <dependency type="executable" location="extensions">textext/asktext.py</dependency>
  <dependency type="executable" location="extensions">textext/typesetter.py</dependency>
  <dependency type="executable" location="extensions">textext/latexlogparser.py</dependency>
  <dependency type="executable" location="extensions">textext/win_app_paths.py</dependency>
  <effect implements-custom-gui="true">
    <object-type>all</object-type>
  </effect>
  <script>
    <command reldir="extensions" interpreter="python">textext/__init__.py</command>
  </script>
  <options silent="true" />
</inkscape-extension>
```

**Comment by Ede123** [comment]
I wasn't aware anybody touched the "dependency" checking code. Are you sure this is a regression in Inkscape itself? I certainly plan to revisit that code soon, though.

Related to this two general comments:
* Usually you don't need to specify all .py files of the extension as dependencies. Someone started it at some point and all extensions copied it, but as you control what you ship with TexText, there's no real reason to re-check at runtime if all files are actually present. My recommendation is, that the mechanism should primarily be used for additional dependencies that are not shipped with the extension itself (e.g. to check the availability of the gimp binary for the .xcf export extension).
* For Inkscape 1.0 there are two related changes in progress / planned:
  * .inx files can go into subdirectories of the "extensions" directory (so you could have the whole extension in a "textext" subdirectory).
  * relative paths in the .inx file could then be relative to the .inx file's parent directory, so paths could omit the "textext/" and the extension would be fully relocatable (i.e. would still work if the folder "textext" was renamed to "textext_beta" or similar).
  * Open question is if we add an additional `reldir` value (e.g. `reldir="inx"`) or if this should simply be the default for relative paths that do not specify `reldir`. (the default for dependencies is currently to look in PATH if `reldir` is not specified, though, which we probably want to keep for backwards-compatibility).

What do you think regarding those suggested changes? Would these be beneficial for TexText? Feel free to let me know (either here or contact me personally or via one of Inkscape's communication channels).

**Comment by jcwinkler** [comment]
@sizmailov I completely uninstalled Inkscape and removed any remaining directories as well as the extension dirs. Then I re-installed everything and now it works. I will investigate this further. I will merge this PR now and open some other PRs later dealing with some fixes reagarding Windows (fixing setup procedure, choco package, non working shortcuts, ...).

@Ede123 

> Usually you don't need to specify all .py files of the extension as dependencies

This works! Thanks for the hint!

> For Inkscape 1.0 there are two related changes in progress / planned:

For me this sounds really good. Lets continue this discussion on the Inkscape site.

**Pull request merged**
