### PR TITLE
Feature/show full log

### LINKED ISSUE #77: Provide full latex output on error
Sometimes latex log parser fails. Full log would be helpful in such cases.

Let's show full latex log if:
  1. latex command fails 
  2. parser fails or finds nothing

It would be default behavior and should cover almost all scenarios. 

Full log still might be helpful even if parser finds errors, lets have a menu item option
`Show latex output` with options:  `Parsed` and `Raw`. 
If `Raw` selected, parser results would be ignored.

### PR DESCRIPTION
**Pull request by sizmailov**
Stdout is hidden (default)
image

Stdout expanded

image

Stderr is empty so not shown 

close #77

### CODE REVIEW

**Comment by sizmailov** [comment]
Updated error dialog:


Default:

image

Expanded and resized

image

**Comment by jcwinkler** [comment]
I reproduced the problem reported in issue #48 (missing package mptopdf and missing permissions for installation on the fly). This issue is perfectly handled by the feature commited by @sizmailov.

**Situation in TexText 0.8.1:**
grafik

**Situation now, after failed compilation**
grafik

**After expanding stderr**
grafik

Unfortunately, the refered log file does not contain helpful information:
```
2018-12-07 15:11:55,227+0100 INFO  pdflatex - starting with command line: "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe" tmp.tex -interaction=nonstopmode -halt-on-error
2018-12-07 15:11:55,227+0100 INFO  pdflatex - allowing known shell commands
2018-12-07 15:11:55,227+0100 INFO  pdflatex - enabling input (output) from (to) processes
2018-12-07 15:11:55,337+0100 FATAL pdflatex - GUI framework cannot be initialized.
2018-12-07 15:11:55,337+0100 FATAL pdflatex - Info: 
2018-12-07 15:11:55,337+0100 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2018-12-07 15:11:55,337+0100 FATAL pdflatex - Line: 73
2018-12-07 15:11:55,337+0100 INFO  pdflatex - finishing with exit code 1
```
Only the hint to the GUI framework shows (to the experienced) user that MiKTeX tried to open its package installation window.

I think we can provide a solution in the FAQ for this case, what do you think @sizmailov ? Or allow MiKTeX to spawn its window, but I think it is a little bit too much to provide such stuff for all available TeX distros...

**Comment by sizmailov** [comment]
The source of problem - missing package. And it should be reported, nothing beyond that. 
We should either 
1) prohibit installation of packages on the fly via command line option if such option exists (then log parser should report about missing package automatically) 
or 
2) tweak log parser to produce meaningful error message in this case

**Comment by sizmailov** [comment]
In addition for can add check for default packages in requirements as you suggested https://github.com/textext/textext/issues/48#issuecomment-443175456

But general procedure to handle missing packages errors is still required.

**Pull request merged**
