### PR TITLE
Improve error handling + setup.py update

### PR DESCRIPTION
**Pull request by sizmailov**
## Error handling 
 + Added a logfile
 + Top-level error collection 
 + Exceptions are in hierarchy and more telling
 + Don't show same error twice (#17)
 + Suppress additional warning window in kde (missing theme)
 + Reduce `return None -> check for None -> raise` to simple `raise` at first place.

todo: if fatal error is unavoidable show it right away

## setup.py
  + each check marked with Succ/Fail/Ukwn (helpful if terminal does not support colors)
  + add option to suppress console colors
  + remove old installation (if any) by default
  + ask for preamble replacement confirmation iff old file exists and differs

### CODE REVIEW

**Comment by sizmailov** [comment]
Github shows changes with default diff algorithm.  `__init__.py` appears to be completely rewritten while it is not the case. `git difftool --minimal <rev1> <rev2>` produces sensible diff.

**Comment by leberwurstsaft** [comment]
> Github shows changes with default diff algorithm. `__init__.py` appears to be completely rewritten while it is not the case. `git difftool --minimal <rev1> <rev2>` produces sensible diff.

I was wondering the same thing. It looks like it was completely altered, which of course isn't the case. But there are whitespace changes all over the place which, I believe, is the reason.

**Comment by sizmailov** [comment]
@leberwurstsaft It's purely algorithm problem, github has option to ignore whitespace changes:

image

**Comment by jcwinkler** [comment]
Sorry guys, sth. is really messed up here. @sizmailov please reopen this pull-request in such a way that it can be merged into the develop branch. Maybe you have to adjust some things on your side. Then I will see how to continue. Too many things in parallel here. My fault. Thanks!

**Comment by sizmailov** [comment]
ok, no problem

**Comment by jcwinkler** [comment]
Thanks, Sergei!

**Pull request merged**
