### PR TITLE
Migration to GTK3+

### PR DESCRIPTION
**Pull request by sizmailov**
Related issue(s): #122 #107 

Replace GTK2 with GTK3

Short checklist:
- [x] Tested with Inkscape version: [0.92.3]
- [x] Tested on Linux, Distro: [Ubuntu 18.04.1]
- [x] Tested on Windows, Version: [fill in Windows version here]
- [ ] Tested on MacOS, Version:  [fill in MacOS version/ name here]

### CODE REVIEW

**Comment by sizmailov** [comment]
I think I changed almost all gtk-involved parts, but I'll revise them once again later.

Almost all changes are one-to-one, but there is a number of deprecated interfaces I replaced. I'll review all the changes in detail a bit later.  

Here is current GTK-3 look of TexText on my system:
image

**Comment by sizmailov** [comment]
I think I can turn this draft to PR shortly

@jcwinkler  The only missing part - is the drop-down arrow for alignment icons. As you found it renders on top of icon on Windows. Old way of removing it definitely doesn't work anymore. We need to check whether change is required for GTK3.

**Comment by jcwinkler** [comment]
Thanks, @sizmailov . I am currently working on the corresponding PyGTK package for Windows. It tuns out that it is not that easy as expected due to tons of crucial depndencies but it should be only a matter of time to get rid of it...

**Comment by jcwinkler** [comment]
grafik

[x] Tested on Windows 8.1, Inkscape 0.92.4

Arrow seems to be OK, too

**Comment by jcwinkler** [comment]
Thanks again for this contribution @sizmailov ! I keep this in a feature branch until the PyGTK-Installer is finalized and reduced to a smart size (currently it's sumo :worried:).

**Pull request merged**
